# Travis CI credentials

language: scala

sudo: required

services:
  - cassandra

scala:
 - "2.10.5"
 - "2.11.6"

# Emails to notify
notifications:
  slack:
    - websudos:P9QNXx1ZGFnDHp3v3jUqtB8k
  email:
    - dev@websudos.co.uk

# Branches to build.
branches:
  only:
    - master
    - develop

jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7

cache:
  directories:
    - $HOME/.ivy2/cache

before_script: travis_retry sbt ++$TRAVIS_SCALA_VERSION update

script: sbt ++$TRAVIS_SCALA_VERSION clean test

